Fix errors related to removal of kubernetes-charts.storage.googleapis.com
Fixes errors like this:

    Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com  
    Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes- 
   charts.storage.googleapis.com/index.yaml : 403 Forbidden